name: {{cookiecutter.project_slug}}
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - scikit-learn>=0.23
  - pandas
  - seaborn
  - matplotlib
  - joblib
  - numpy
  - pyyaml
  - pip
  - absl-py
  {% if cookiecutter.use_pytest == 'y' -%}
  - pytest
  - pytest-dependency
  {%- endif %}